0x API price clarification and allowance guide
0xProject/website pull request #234
Opened 2020-02-06 21:52 UTC by fragosti

- Clarifies what `price` means. 
- Creates a new setting allowance guide. 
- Refers to allowance guide and fixes some small issues.

<img width="1408" alt="Screen Shot 2020-02-06 at 1 49 03 PM" src="https://user-images.githubusercontent.com/3066135/73981709-a7ea0b00-48e7-11ea-8923-74d91721ab60.png">
<img width="1354" alt="Screen Shot 2020-02-06 at 1 49 16 PM" src="https://user-images.githubusercontent.com/3066135/73981719-b0424600-48e7-11ea-99ae-7b6bc5c15dfb.png">
<img width="1253" alt="Screen Shot 2020-02-06 at 1 49 22 PM" src="https://user-images.githubusercontent.com/3066135/73981730-bafcdb00-48e7-11ea-94ec-629bfe3de800.png">

2020-02-10 00:02 UTC, dave4506 reviewed
Very minor nits but nice to see this exist now!

2020-02-10 00:02 UTC, dave4506 commented on mdx/guides/how-to-set-your-token-allowances.mdx
> +You can read more about [the ERC20 token allowance function](https://tokenallowance.io/), but this guide will focus on how to set them.
Should we add a quick blurb for which contracts to approve for basic situations or ways to understand when or why you would approve the staking proxy, etc.

2020-02-10 00:02 UTC, dave4506 commented on mdx/guides/how-to-set-your-token-allowances.mdx
> +Here we will use Etherscan as they allow you to interact with any smart contract.
Statement felt little confusing, it is correct but had to take a double take to understand it.

2020-02-10 20:57 UTC, xianny commented on mdx/guides/how-to-set-your-token-allowances.mdx
> +To set your WETH allowance for the ERC20AssetProxy contract you can navigate to the [Dapp view for the WETH ERC20](https://etherscan.io/dapp/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#writeContract)
Nit: `the 0x ERC20AssetProxy contract`

2020-02-10 21:02 UTC, xianny commented on mdx/guides/how-to-set-your-token-allowances.mdx
> +![Setting an approval in Etherscan!](/images/docs/approval.png)
Can we include an explanation:
> Provide the address of the 0x ERC20AssetProxy contract. The updated address can be found in @0x/contract-addresses https://github.com/0xProject/0x-monorepo/blob/development/packages/contract-addresses/addresses.json#L5

2020-02-10 21:05 UTC, xianny requested changes
Yay, thanks for doing this. Looks great!

Nit: The guide refers to `ERC20AssetProxy` contract in a few places, but the name of the contract is `ERC20Proxy` in the node packages and contract files. Can we call it `0x ERC20Proxy smart contract` or `0x ERC20 asset proxy smart contract` in the guides? Or whatever you think sounds good, I just think we should stay away from using `ERC20AssetProxy` as a name because it could be confusing.

2020-02-11 02:42 UTC, fragosti commented on mdx/guides/how-to-set-your-token-allowances.mdx
> +You can read more about [the ERC20 token allowance function](https://tokenallowance.io/), but this guide will focus on how to set them.
I just went for a rephrase here.

2020-02-11 20:13 UTC, xianny approved these changes

2020-02-11 20:14 UTC, merged