Margin trading guide with 0x API
0xProject/website pull request #239
Opened 2020-02-13 22:45 UTC by dave4506

^ 

If you have the time please skim the codebase https://github.com/0xProject/0x-api-starter-guide-code for any typos or oversights on my part.

2020-02-18 22:44 UTC, fragosti approved these changes

2020-02-25 00:54 UTC, jalextowle requested changes

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +        EXCHANGE = IExchange(_exchange);
These should be lower-case because they aren't actually constants (we're setting them right here). 

In our production smart contracts, we would actually prefer to use constants for all of these addresses. If you check out the staking contracts, you'll find the deployment constants pattern. That is how we would actually write this, so you'll need to make a call between the added complexity of the pattern vs. the fact that the current style of initialization is sub-optimal for production smart contracts.

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +  positionBalance = msg.value.safeSub(quote.protocolFeeAmount);
The `protocolFeeAmount` can be calculated as `protocolFeeAmount = tx.gasPrice.safeMul(exchange.protocolFeeMultiplier());`. As I mentioned offline, I think this should be calculated on-chain for DevEx reasons.

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +  positionBalance = msg.value.safeSub(quote.protocolFeeAmount);
Thinking about this more, this guide might be the right place to introduce the various ways in which protocol fees can be handled by a calling contract. Maybe we should take WETH from `msg.sender` if `msg.value < protocolFeeAmount` instead of reverting.

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +assert(CDAI.borrow(quote.sellAmount) == 0);
We should use `require` instead of `assert` in almost all cases. We should only use `assert` for things that shouldn't ever happen in production (and even then, there is still an argument to use `require`). Additionally, we should add a revert reason. You can do this by adding a string argument to `require`:

```
require(true, "This is the error message");
```

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +require(quote.buyToken == address(DAI), "not buying WETH");
Is this the right error message?

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +LibFillResults.FillResults memory fillResults = abi.decode(data (LibFillResults.FillResults));
Will this compile? Are you missing a comma?

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +positionBalance += fillResults.makerAssetFilledAmount;
We should never use arithmetic operators. Let's use `positionBalance = positionBalance.safeAdd(fillResults.makerAssetFilledAmount)` here.

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +        positionBalance += fillResults.makerAssetFilledAmount;
Ditto here

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +uint256 daiBorrowBalance = CDAI.borrowBalanceCurrent(address(this)); // TODO
Why do we have a `TODO` here?

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +    assert(CDAI.repayBorrow(fillResults.makerAssetFilledAmount) == 0);
As stated above, let's use `require` (unless I'm missing context), and add an error message.

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +    assert(CETH.redeem(CETH.balanceOfUnderlying(address(this))) == 0); // TODO correct?
Ditto + remove the `TODO` please

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +    require(wethBalance > quote.sellAmount, "not enough to swap");
We would typically bundle up a bunch of these `require` statements into a function. That may make the guide harder to read, but it's something to consider.

2020-02-25 00:54 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +    uint256 daiBorrowBalance = CDAI.borrowBalanceCurrent(address(this)); // TODO
nit: `TODO`

2020-03-02 16:28 UTC, dave4506 commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +  positionBalance = msg.value.safeSub(quote.protocolFeeAmount);
Good point, I was considering this guide to gloss over those subjects, namely this is the first guide for people to piece together how 0x API can fulfill roles that of Uniswap. I feel like all the nuances with protocol fees can be better handled in a dedicated guide that contains all that content.

2020-03-02 16:33 UTC, dave4506 commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +        EXCHANGE = IExchange(_exchange);
Making the call to use the pattern above to make it easier to gloss over and understand what is happening. Mainly, if people want to develop on a testnet, I'm hoping readers do not have to manipulate the sol file and migration/deployment system to do so. Seem like this pattern creates that better dev ex (for readability). Will lower case them per your comment.

2020-03-02 17:05 UTC, fragosti approved these changes

2020-03-02 17:08 UTC, jalextowle commented on mdx/guides/develop-a-margin-trading-smart-contract-with-0x-api.mdx
> +  positionBalance = msg.value.safeSub(quote.protocolFeeAmount);
Hmm, yeah that's probably a good call. I think having that guide would be really useful though.

2020-03-05 19:48 UTC, merged