Updates 0x API parameters documentation for RFQ
0xProject/website pull request #318
Opened 2020-07-27 20:54 UTC by PirosB3

2020-07-27 22:46 UTC, steveklebanoff requested changes

2020-07-27 22:46 UTC, steveklebanoff commented on mdx/api/index.mdx
> +| `includedSources`    | (Optional) For now only supports `RFQT`, which should be used when the integrator only wants RFQT liquidity without any other DEX orders. Requires a particular agreement with
IMHO I think we should leave these RFQT params out for now until we get the complete RFQT documentation out

2022-08-17 15:21 UTC, feuGeneA commented
Hi Daniel! Would you mind closing out this PR or at least removing me from the Reviewers? I'd love to get it off my list. I hope you've been well! Thank you!

2023-10-27 12:24 UTC, feuGeneA commented
Hi @PirosB3 ! Would you mind closing out this PR or at least removing me from the Reviewers? I'd love to get it off my list of pending review requests. I hope you've been well! Thank you!

2023-10-27 13:47 UTC, closed without merging