RFQ-T docs
0xProject/website pull request #322
Opened 2020-08-03 17:23 UTC by feuGeneA

To view the rendering locally, edit `/etc/hosts` to alias 127.0.0.1 to `0xproject.localhost`, check out the repo, do `yarn`, then `dev`, then navigate to, eg, https://0xproject.localhost:3572/docs/guides/understanding-rfqt

2020-08-03 17:25 UTC, feuGeneA commented
For convenience, here's a quick view of the rendering of the beginning of the main guide as it stands right now:
![image](https://user-images.githubusercontent.com/7883777/89209629-af375c00-d58c-11ea-85cd-8eb80ad86921.png)

2020-08-03 20:34 UTC, feuGeneA commented on mdx/api/index.mdx
> +RFQ-T liquidity can only be accessed if the request supplies a taker address, a permissioned API key via header `0x-api-key`, and the query parameter `intentOnFilling=true`.  For more details see the
Need to also prescribe here the inclusion of a `takerAddress`.

2020-08-03 20:35 UTC, feuGeneA commented on mdx/api/index.mdx
> +RFQ-T liquidity can only be accessed if the request supplies a taker address, a permissioned API key via header `0x-api-key`, and the query parameter `intentOnFilling=true`.  For more details see the
Need to also prescribe here the inclusion of a non-null `takerAddress` query param in the request.

2020-08-03 21:31 UTC, PirosB3 commented on mdx/api/index.mdx
> +RFQ-T liquidity can only be accessed if the request supplies a taker address, a permissioned API key via header `0x-api-key`, and the query parameter `intentOnFilling=true`.  For more details see the
Just to check, do we need a "What is RFQT liquidity" chapter, or can we assume it somehow? my understanding is that this documentation will be rendered on the main webpage, therefore we may need an introduction.

2020-08-03 21:31 UTC, PirosB3 commented on mdx/api/index.mdx
> +RFQ-T liquidity can only be accessed if the request supplies a taker address, a permissioned API key via header `0x-api-key`, and the query parameter `intentOnFilling=true`.  For more details see the
The integrator needs to also ensure that `excludedSources` key does not contain `Native` or `0x`.

2020-08-03 21:31 UTC, PirosB3 commented on mdx/api/index.mdx
> +An RFQ-T quote can be identified by its inclusion of one or more orders with a `takerAddress` matching the `takerAddress` that was supplied in the request.  However, the lack of such an order in a qu
it's inclusion. Typo?

2020-08-03 21:31 UTC, PirosB3 commented on mdx/api/index.mdx
> +<HttpCall fontSize="16px" path="/swap/v0/quote?buyToken=WETH&sellToken=ETH&buyAmount=10000000&takerAddress=0xffffffffffffffffffffffffffffffffffffffff" />
What kind of request is this? selling `1e-11` WETH for ETH?

2020-08-03 21:31 UTC, PirosB3 commented on mdx/guides/understanding-rfqt.mdx
> +RFQ is an abbreviation of Request for Quote, in that the 0x API requests quotes from market makers on behalf of its clients. The -T suffix indicates that the settlement transaction is to be submitted
💯

2020-08-03 21:31 UTC, PirosB3 commented on mdx/guides/understanding-rfqt.mdx
> +The 0x API now automatically attempts to supplement every quote with RFQ-T liquidity. The biggest determinant of whether such live quotes will be aggregated with other liquidity sources is whether th
RFQT liquidity is only supplied to the integrator, if they have an agreement (technically speaking, an API key) with us.

2020-08-03 21:31 UTC, PirosB3 commented on mdx/guides/understanding-rfqt.mdx
> +Trusted takers are identified by an API key, specified in the HTTP header `0x-api-key`. In addition, to qualify for RFQ-T liquidity, the request must also specify a non-null `takerAddress` query para
This is kind of repetitive and already covered in `mdx/api/index.mdx`, have you considered having 1 document link to the other? this way, we don't have to maintain content on both pages.

2020-08-03 21:31 UTC, PirosB3 commented on mdx/guides/understanding-rfqt.mdx
> +For the instance at `api.0x.org`, the 0x team is maintaining a list of trusted market makers, which at this time includes 0x's own Periscope Trading, as well as a handful of other trusted partners.
It would be nice to link out to [this article](https://blog.0xproject.com/introducing-0x-labs-and-periscope-trading-c5f84879e782)

2020-08-03 21:31 UTC, PirosB3 commented on mdx/guides/understanding-rfqt.mdx
> +The 0x API offers two different endpoints for the use of RFQ-T. One is an "indicative pricing" endpoint, hosted at `/swap/vX/price`. This endpoint responds with pricing information, but that response
I see what you are doing with `vX`, however, do you think it's worth specifying somewhere that `vX` is the latest version. Just to ensure 100% no ambiguity?

2020-08-03 21:31 UTC, PirosB3 commented on mdx/guides/understanding-rfqt.mdx
> +0x API clients should strictly adhere to a rule of using indicative pricing by default, and of only requesting firm quotes when the user is actually intent on filling. For example, a continuously upd
great examples! 💯

2020-08-03 21:33 UTC, PirosB3 requested changes
@blakehendo should we also mention the new `includedSources` parameter?

Gene the doc is a great start, I always admire your way of describing things very easily with simple words. Let me know when I should do a second review

2020-08-05 22:13 UTC, feuGeneA commented
I've pushed a complete draft of the main Guide.  It's currently deployed to staging, accessible at https://0xproject.localhost:3572/docs/guides/rfqt-in-the-0x-api

2020-08-12 14:55 UTC, PirosB3 commented on mdx/api/index.mdx
> +| `skipValidation`     | (Optional) Normally, whenever a `takerAddress` is provided, the API will validate the quote for the user. (For more details, see ["How does `takerAddress` help with catching
Hey Gene, so I think me and you need to sync about RFQT params. I still have [this PR](https://github.com/0xProject/website/pull/318/files) open that I was wanting to merge when RFQ is out. Do you think it's worth merging mine in yours?

2020-08-12 14:58 UTC, PirosB3 approved these changes
This is great. I have a few questions:

- Are we not going to be covering the V1 endpoints?
- It would be nice to merge my small PR into your PR (I suggested that in the comments)

2020-08-12 14:58 UTC, PirosB3 commented on mdx/guides/unlocking-meta-transaction-swaps.mdx
> -    await window.web3.eth.sendTransaction(await response.json());
was this removed by mistake?

2020-08-13 23:32 UTC, steveklebanoff reviewed
A few comments but overall looks good to go -- great work!

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/api/index.mdx
> +<HttpCall fontSize="16px" path="/swap/v0/quote?sellToken=WETH&buyToken=DAI&sellAmount=1000000000000000000&takerAddress=0xffffffffffffffffffffffffffffffffffffffff&intentOnFilling=true" />
![image](https://user-images.githubusercontent.com/210914/90185651-e3b8ce00-dd6b-11ea-8d2b-0c620d2f20e0.png)

This falls off out of the grey box - can we make the font smaller or break into multiple lines?

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/api/index.mdx
> +Identical to the response schema for `/swap/v0/quote`, with one exception: the `orders` property will always be undefined.
nit, but would prefer to say there is no `orders` key on the object returned.

the way this is written makes me feel like I would expect an `orders` key to be in the object, and it explicitly set to `undefined`

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/api/index.mdx
> +<HttpCall path="/swap/v0/price?sellToken=WETH&buyToken=DAI&sellAmount=1000000000000000000" />
I think we should include a taker address in the example since this is expected when using RFQT

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/api/index.mdx
> +Identical to the request schema for `/swap/v0/quote`, with one exception: the `skipValidation` parameter will always be considered to be `true`, even when a `takerAddress` has been specified.
Should we note that they should send in a takerAddress if possible for the most accurate RFQT pricing?

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/api/index.mdx
> +| `excludedSources`    | (Optional) Liquidity sources (`Eth2Dai`, `Uniswap`, `Kyber`, `0x`, `LiquidityProvider` etc) that will not be included in the provided quote. Ex: `excludedSources=Uniswap,Kybe
If we are going to do this call-out of Native sources here, should we do it everywhere we describe `excludedSources`?

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/market-making-on-0x.mdx
> +In addition to relayer hosting, distribution can also be achieved via Mesh, a peer-to-peer network built specifically for sharing 0x orders. For more information, see [0x.org/mesh](0x.org/mesh).
Nice addition 👍

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/market-making-on-0x.mdx
> +Whereas posting orders, to a relayer or to Mesh, represents a "push" distribution model, there is an alternative "pull" model as well, known as Request for Quote (RFQ).  This is a feature of the [0x
Nice 👍

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/market-making-on-0x.mdx
> +Explicitly cancelling orders always requires an on-chain transaction. However, you may create short lived orders and replace the expired orders without any on-chain transactions. Due to the variabili
I feel like this 5 minute number should be updated, perhaps we can ask @alexkroeger if we have any stats we could pull here

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/rfqt-in-the-0x-api.mdx
> +In practice, such losses are largely at the hands of one particular class of takers: arb bots. If makers share orders with an unspecified/null taker address, as is typical in Mesh order sharing, then
Suggestion: `arb` -> `arbitrage`

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/rfqt-in-the-0x-api.mdx
> +In order to retain access to RFQ-T liquidity, it's important for clients of the 0x API to be good citizens of the marketplace. For end users of trusted integrations, being a good citizen means actual
Feels a little weird to use "indicative" and "firm" quotes here without first introducing what they are. That being said, we introduce them immediately afterwards, so seems OK 👍

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/rfqt-in-the-0x-api.mdx
> +When a market maker provides a fillable quote, which can be settled by the taker's submitting it to the 0x protocol, the taker has an expectation that the swap will actually settle, that it won't rev
I don't think all market makers are doing this exactly as described, they are likely taking an educated guess on the likelihood that the user will actually fill, and not 100% reserving funds for every firm quote they give out.

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/rfqt-in-the-0x-api.mdx
> +The firm quote resource is hosted at [`/swap/v0/quote`](/docs/api#get-swapv0quote) and responds with a full 0x order, which can be submitted to an Ethereum node by the client. Therefore it is expecte
Referring to "full 0x order" seems a bit confusing as /quote contains calldata that is made up of potentially many orders. Perhaps we say something like "responds with on-chain fillable calldata"

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/rfqt-in-the-0x-api.mdx
> +The firm quote resource is hosted at [`/swap/v0/quote`](/docs/api#get-swapv0quote) and responds with a full 0x order, which can be submitted to an Ethereum node by the client. Therefore it is expecte
Also -- not 100% necessary -- but perhaps we start off with something like "Requesting a firm quote utilizes the existing the /swap/v0/quote with some additional required parameters"

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/rfqt-in-the-0x-api.mdx
> +0x API clients should strictly adhere to a rule of using indicative pricing by default, and of only requesting firm quotes when the user is actually intent on filling. For example, a continuously upd
Great description 👍

2020-08-13 23:32 UTC, steveklebanoff commented on mdx/guides/rfqt-in-the-0x-api.mdx
> +-   `takerAssetAmount` equal to or less than the `takerAssetAmount` given in the request.
We actually accept if it is more -- some MMers do this to avoid rounding issues

2020-08-14 20:37 UTC, merged