Query 0x API and render pools data
0xProject/website pull request #62
Opened 2019-11-20 03:21 UTC by fragosti

<img width="1680" alt="Screen Shot 2019-11-19 at 7 02 34 PM" src="https://user-images.githubusercontent.com/3066135/69206433-81df7680-0b01-11ea-8fcb-44d2a3175482.png">

2019-11-20 20:16 UTC, kimpers requested changes

2019-11-20 20:16 UTC, kimpers commented on ts/pages/staking/home.tsx
> +    });
Correct me if I'm wrong but `useEffect` with no second arg would trigger on every component render and re-fetch the data. We would rather fetch it only once on page load right?
```suggestion
    }, []);
```

2019-11-20 20:16 UTC, kimpers commented on ts/utils/configs.ts
> +    API_BASE_DEV_URL: 'http://localhost:3000',
NIT: I think `website-backend` defaults to using port `3000` for http, would be nice if they don't conflict when running locally.

2019-11-20 21:48 UTC, fragosti commented on ts/pages/staking/home.tsx
> +    });
Oops!

2019-11-20 23:27 UTC, fragosti commented on ts/utils/configs.ts
> +    API_BASE_DEV_URL: 'http://localhost:3000',
In here `BACKEND_BASE_DEV_URL` is using port 3001 already so they do not conflict.

2019-11-21 19:54 UTC, kimpers approved these changes

2019-11-21 19:54 UTC, kimpers commented on package.json
> +        "redux": "^4.0.4",
🎉

2019-11-21 19:57 UTC, merged